// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"forgejo.org/modules/jwtx"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalIssuer creates a new instance of MockInternalIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalIssuer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockInternalIssuer {
	mock := &MockInternalIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalIssuer is an autogenerated mock type for the InternalIssuer type
type MockInternalIssuer struct {
	mock.Mock
}

type MockInternalIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalIssuer) EXPECT() *MockInternalIssuer_Expecter {
	return &MockInternalIssuer_Expecter{mock: &_m.Mock}
}

// IssuerPlaceholder provides a mock function for the type MockInternalIssuer
func (_mock *MockInternalIssuer) IssuerPlaceholder() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IssuerPlaceholder")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInternalIssuer_IssuerPlaceholder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssuerPlaceholder'
type MockInternalIssuer_IssuerPlaceholder_Call struct {
	*mock.Call
}

// IssuerPlaceholder is a helper method to define mock.On call
func (_e *MockInternalIssuer_Expecter) IssuerPlaceholder() *MockInternalIssuer_IssuerPlaceholder_Call {
	return &MockInternalIssuer_IssuerPlaceholder_Call{Call: _e.mock.On("IssuerPlaceholder")}
}

func (_c *MockInternalIssuer_IssuerPlaceholder_Call) Run(run func()) *MockInternalIssuer_IssuerPlaceholder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalIssuer_IssuerPlaceholder_Call) Return(s string) *MockInternalIssuer_IssuerPlaceholder_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInternalIssuer_IssuerPlaceholder_Call) RunAndReturn(run func() string) *MockInternalIssuer_IssuerPlaceholder_Call {
	_c.Call.Return(run)
	return _c
}

// SigningKey provides a mock function for the type MockInternalIssuer
func (_mock *MockInternalIssuer) SigningKey() jwtx.SigningKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SigningKey")
	}

	var r0 jwtx.SigningKey
	if returnFunc, ok := ret.Get(0).(func() jwtx.SigningKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwtx.SigningKey)
		}
	}
	return r0
}

// MockInternalIssuer_SigningKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SigningKey'
type MockInternalIssuer_SigningKey_Call struct {
	*mock.Call
}

// SigningKey is a helper method to define mock.On call
func (_e *MockInternalIssuer_Expecter) SigningKey() *MockInternalIssuer_SigningKey_Call {
	return &MockInternalIssuer_SigningKey_Call{Call: _e.mock.On("SigningKey")}
}

func (_c *MockInternalIssuer_SigningKey_Call) Run(run func()) *MockInternalIssuer_SigningKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalIssuer_SigningKey_Call) Return(signingKey jwtx.SigningKey) *MockInternalIssuer_SigningKey_Call {
	_c.Call.Return(signingKey)
	return _c
}

func (_c *MockInternalIssuer_SigningKey_Call) RunAndReturn(run func() jwtx.SigningKey) *MockInternalIssuer_SigningKey_Call {
	_c.Call.Return(run)
	return _c
}
